"""
Solution Knowledge Base models.

These tables implement the "learning loop" requested in the brief:

  - SolutionPattern : one row per *distinct error signature*. It accumulates
                      across occurrences. Each time the agent diagnoses an
                      error we either match an existing pattern (KNOWN error)
                      or create a new one (NEW error). When a human ACCEPTS a
                      fix (approves the PR / remediation), we reinforce the
                      pattern: occurrence + acceptance counters go up and the
                      confidence score is recomputed. The more times the same
                      fix has been accepted for the same signature, the higher
                      the confidence — which is exactly what lets the agent
                      flip an error from "analysis only" to "auto-write code +
                      raise PR".

  - SolutionFix     : the concrete code change(s) tied to a pattern. Populated
                      either by the LLM (for a known error) or ingested from a
                      human-merged PR (closing the loop so the agent can reuse
                      the real diff next time).

Both tables are additive — they don't touch existing schema, so dropping this
file in and registering the models is safe for an existing DB (the tables are
created on next startup via Base.metadata.create_all).
"""
from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float, ForeignKey, Integer, JSON,
    String, Text,
)
from sqlalchemy.orm import relationship

from app.core.database import Base


class SolutionStatus(str, enum.Enum):
    PROPOSED  = "PROPOSED"    # created from an LLM diagnosis, not yet accepted
    KNOWN     = "KNOWN"       # accepted at least once — agent trusts it
    DEPRECATED = "DEPRECATED" # superseded / no longer applicable


class FixOrigin(str, enum.Enum):
    LLM            = "LLM"            # generated by the model
    HUMAN_PR       = "HUMAN_PR"       # ingested from a merged human PR
    RUNBOOK        = "RUNBOOK"        # derived from an uploaded runbook


class SolutionPattern(Base):
    """A reusable solution keyed by a normalized error signature."""

    __tablename__ = "solution_patterns"

    id            = Column(Integer, primary_key=True, autoincrement=True)

    # The fingerprint used for known-vs-new matching. Built by
    # error_signature.compute_signature() — a stable hash of the normalized
    # error text (numbers/ids/paths/timestamps stripped).
    signature     = Column(String(64), unique=True, index=True, nullable=False)

    # Human-readable label + the canonical error text we matched on.
    title         = Column(String(512), nullable=False)
    error_excerpt = Column(Text, default="")

    # Classification used for routing + code-gen prompting.
    category      = Column(String(64),  default="General")   # ADF / Databricks / Git / AWS Glue / General
    component     = Column(String(128), nullable=True)       # connector type or subsystem
    error_type    = Column(String(128), nullable=True)       # e.g. "KeyError", "SchemaDrift", "Timeout"
    support_group = Column(String(128), nullable=True)       # team/group routing key

    # The diagnosis carried by this pattern.
    root_cause    = Column(Text, default="")
    fix_summary   = Column(Text, default="")
    fix_steps     = Column(JSON, default=list)               # ["step 1", "step 2", ...]

    # Reinforcement state — this is the heart of requirement #3.
    occurrence_count = Column(Integer, default=1)   # times this signature was seen
    acceptance_count = Column(Integer, default=0)   # times a human accepted the fix
    rejection_count  = Column(Integer, default=0)   # times a human rejected the fix
    confidence       = Column(Float,   default=0.0) # 0..1, recomputed on each event

    status        = Column(Enum(SolutionStatus), default=SolutionStatus.PROPOSED, index=True)

    first_seen_at = Column(DateTime, default=datetime.utcnow)
    last_seen_at  = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_accepted_at = Column(DateTime, nullable=True)

    fixes = relationship(
        "SolutionFix",
        back_populates="pattern",
        cascade="all, delete-orphan",
        order_by="desc(SolutionFix.created_at)",
    )

    # ── derived helpers ────────────────────────────────────────────────
    @property
    def is_auto_fixable(self) -> bool:
        """A pattern is trusted enough to auto-write code + raise a PR when it
        has at least one accepted human fix AND confidence clears the bar."""
        return (
            self.status == SolutionStatus.KNOWN
            and self.acceptance_count >= 1
            and (self.confidence or 0.0) >= 0.7
            and any(f.has_code for f in (self.fixes or []))
        )


class SolutionFix(Base):
    """A concrete code change attached to a SolutionPattern."""

    __tablename__ = "solution_fixes"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    pattern_id    = Column(Integer, ForeignKey("solution_patterns.id", ondelete="CASCADE"),
                           nullable=False, index=True)

    origin        = Column(Enum(FixOrigin), default=FixOrigin.LLM)

    # The change itself. We support two shapes:
    #   - file_path + new_content  → full-file replacement (easiest to commit)
    #   - diff                     → unified diff (kept for human review)
    file_path     = Column(String(1024), nullable=True)
    new_content   = Column(Text, nullable=True)
    diff          = Column(Text, nullable=True)

    explanation   = Column(Text, default="")
    language      = Column(String(32), nullable=True)

    # Provenance when ingested from a merged PR (requirement: ingest PR logs
    # back into the KB so the same issue can be auto-fixed next time).
    pr_url        = Column(String(512), nullable=True)
    pr_number     = Column(Integer, nullable=True)
    merged_by     = Column(String(255), nullable=True)

    created_at    = Column(DateTime, default=datetime.utcnow, index=True)

    pattern = relationship("SolutionPattern", back_populates="fixes")

    @property
    def has_code(self) -> bool:
        return bool((self.new_content and self.file_path) or self.diff)
